name: Capslock compare
description: Capslock compare

inputs:
  go-version:
    default: "1.24.6"
    required: true
    description: "Go version used"
  capslock-version:
    default: "v0.2.8"
    required: true
    description: "Capslock version used"
  scope:
    default: ""
    required: true
    description: "The scope of analysis"
  main-branch:
    default: "main"
    required: true
    description: "Name of the main branch"
  output-place:
    default: "pr-comment"
    required: true
    description: "Output place"
runs:
  using: composite
  steps:
    - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version: "${{ inputs.go-version }}"
    - name: Cache capslock
      id: capslock-cache
      uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
      with:
        path: ~/go/bin
        key: ${{ runner.os }}-${{ runner.arch }}-capslock-${{ inputs.capslock-version }}
    - shell: bash
      if: steps.capslock-cache.outputs.cache-hit != 'true'
      id: capslock-install
      env:
        CAPSLOCK_VERSION: ${{ inputs.capslock-version }}
      run: |
        go install "github.com/google/capslock/cmd/capslock@${CAPSLOCK_VERSION}"
    - shell: bash
      id: capslock-run
      env:
        MAIN_BRANCH: ${{ inputs.main-branch }}
        SCOPE: ${{ inputs.scope }}
        CAPSLOCKTOOLSTMPDIR: ${{ runner.temp }}
        OUTPUT_PLACE: ${{ inputs.output-place }}
      run: |
        ${GITHUB_ACTION_PATH}/capslock.sh
    - uses: marocchino/sticky-pull-request-comment@773744901bac0e8cbb5a0dc842800d45e9b2b405 # v2.9.4
      if: steps.capslock-run.outputs.output != ''
      with:
        hide_and_recreate: true
        hide_classify: "OUTDATED"
        message: |
          ${{steps.capslock-run.outputs.output}}
