name: Setup jrsonnet
description: Setup jrsonnet CLI and add it to the PATH, this action will pull the binary from GitHub releases and store it in cache for the next run.

inputs:
  cache-prefix:
    description: Prefix for the cache key.
    default: jrsonnet

  version:
    description: |
      Version of the jrsonnet CLI to install.
    default: 0.5.0-pre96-test

outputs:
  cache-hit:
    description: Whether the cache was hit or not.
    value: ${{ steps.cache.outputs.cache-hit || 'false' }}

runs:
  using: composite

  steps:
    - name: Setup cache
      id: cache
      uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      with:
        path: ${{ github.workspace }}/bin/jrsonnet
        key: ${{ inputs.cache-prefix }}-${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}

    - name: Map OS and ARCH to jrsonnet release artifact
      if: steps.cache.outputs.cache-hit != 'true'
      shell: sh
      run: |
        echo "OS=$(go env GOOS)" >> "$GITHUB_ENV"
        echo "ARCH=$(go env GOARCH)" >> "$GITHUB_ENV"

    - name: Fetch GitHub Release Asset
      id: fetch_asset
      if: steps.cache.outputs.cache-hit != 'true'
      uses: dsaltares/fetch-gh-release-asset@aa2ab1243d6e0d5b405b973c89fa4d06a2d0fff7 # 1.1.2
      with:
        repo: "CertainLach/jrsonnet"
        version: "tags/v${{ inputs.version }}"
        file: "jrsonnet-${{ env.OS }}-${{ env.ARCH }}"
        target: ${{ github.workspace }}/bin/jrsonnet

    - name: make executable
      id: executable
      if: steps.fetch_asset.outcome == 'success'
      shell: sh
      run: |
        chmod +x ${{ github.workspace }}/bin/jrsonnet

    - name: Add binary to path
      shell: sh
      run: |
        # Check if `jrsonnet` is already in the PATH
        if command -v jrsonnet >/dev/null; then
          echo "jrsonnet is already in the PATH, not re-adding it"
          exit 0
        fi

        echo "Adding '${{ github.workspace }}/bin' to the PATH so the 'jrsonnet' binary can be found"
        echo "${{ github.workspace }}/bin" >> "${GITHUB_PATH}"
