# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/actions/lint-pr-title"
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "-"

  - package-ecosystem: "gomod"
    directory: "/actions/trigger-argo-workflow"
    schedule:
      interval: "weekly"
    groups:
      go:
        applies-to: "version-updates"
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/actions/techdocs-rewrite-relative-links"
    schedule:
      interval: "weekly"
    groups:
      go:
        applies-to: "version-updates"
        patterns:
          - "*"
