# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: "gomod"
    cooldown:
      default-days: 5
      semver-major-days: 14
      semver-minor-days: 5
      semver-patch-days: 0
    directory: "/actions/trigger-argo-workflow"
    schedule:
      interval: "weekly"
    groups:
      go:
        applies-to: "version-updates"
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    cooldown:
      default-days: 5
      semver-major-days: 14
      semver-minor-days: 5
      semver-patch-days: 0
    directory: "/actions/techdocs-rewrite-relative-links"
    schedule:
      interval: "weekly"
    groups:
      go:
        applies-to: "version-updates"
        patterns:
          - "*"
