name: syft-sbom-ci
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  syft-sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.0.0
      - name: Anchore SBOM Action
        uses: anchore/sbom-action@ab5d7b5f48981941c4c5d6bf33aeb98fe3bae38c # 0.15.10
        with:
          artifact-name: ${{ github.event.repository.name }}-spdx.json
