name: Publish Docker image
description: Publish docker images to DockerHub

inputs:
  repository:
    description: |
      The caller workflow's repository
  tags:
    description: |
      List of Docker images to be pushed.
    required: true
  context:
    description: |
      Path to Dockerfile, which is used to build the image.
    default: "."
  push:
    description: |
      Push the generated images also to DockerHub
    default: "false"

runs:
  using: composite
  steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: grafana/shared-workflows/actions/dockerhub-login@main
      with:
        common_secrets: |
          DOCKERHUB_USERNAME=dockerhub:username
          DOCKERHUB_PASSWORD=dockerhub:password

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ inputs.repository }}
        tags: ${{ inputs.tags }}

    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: ${{ inputs.context }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
