name: Publish Docker image
description: Publish docker images to DockerHub

inputs:
  repository:
    description: |
      The caller workflow's repository
  tags:
    description: |
      List of Docker images to be pushed.
    required: true
  context:
    description: |
      Path to the Docker build context.
    default: "."
  platforms:
    description: |
      List of platforms to build the image for
    required: false
  push:
    description: |
      Push the generated images also to DockerHub
    default: "false"
  file:
    description: |
      The dockerfile to use. Defaults to {context}/Dockerfile.
    default: ""

runs:
  using: composite
  steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: grafana/shared-workflows/actions/dockerhub-login@main

    # If platforms is specified then also initialize buildx and qemu:
    - name: Set up QEMU
      if: inputs.platforms
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      if: inputs.platforms
      uses: docker/setup-buildx-action@v3

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ inputs.repository }}
        tags: ${{ inputs.tags }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5.0.0
      with:
        context: ${{ inputs.context }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: ${{ if(ne(inputs.file, ''), inputs.file, inputs.context + '/Dockerfile') }}