name: Build & Publish Docker image
description: Build and publish docker images to DockerHub

inputs:
  repository:
    description: |
      Docker repository name (**required**)
  tags:
    description: |
      Tags that should be used for the image (see the [metadata-action][mda] for details)
    required: true
  labels:
    description: |
      List of custom labels to be added to the image.
    required: false
  context:
    description: |
      Path to the Docker build context.
    default: "."
  platforms:
    description: |
      List of platforms the image should be built for (e.g. `linux/amd64,linux/arm64`)
    required: false
  push:
    description: |
      Push the generated image
    default: "false"
  file:
    description: |
      Path and filename of the dockerfile to build from. (Default: `{context}/Dockerfile`)
    required: false
  build-args:
    description: |
      List of arguments necessary for the Docker image to be built.
    required: false
    default: ""
  target:
    description: |
      Sets the target stage to build
    required: false
  cache-from:
    description: |
      Where cache should be fetched from.
      Passed to [docker/build-push-action](https://github.com/docker/build-push-action?tab=readme-ov-file#inputs).

      [More about GHA and container caching](https://www.kenmuse.com/blog/implementing-docker-layer-caching-in-github-actions/)
    default: "type=gha"
  cache-to:
    description: |
      Where cache should be stored to.
      Passed to [docker/build-push-action](https://github.com/docker/build-push-action?tab=readme-ov-file#inputs).

      [More about GHA and container caching](https://www.kenmuse.com/blog/implementing-docker-layer-caching-in-github-actions/)
    default: "type=gha,mode=max"
  docker-buildx-driver:
    description: |
      The [driver](https://github.com/docker/setup-buildx-action/tree/v3/?tab=readme-ov-file#customizing) to use for Docker Buildx
    required: false
    default: "docker-container"
  secrets:
    description: |
      Secrets to [expose to the build](https://github.com/docker/build-push-action). Only needed when authenticating to private repositories outside the repository in which the image is being built.
    required: false
  load:
    description: |
      Whether to load the built image into the local docker daemon.
    required: false
    default: "false"

runs:
  using: composite
  steps:
    # See this conversation for more context as to why we don't want to allow pushes on pull requests
    # https://github.com/grafana/shared-workflows/pull/143#discussion_r1628314620
    - name: Check if push is allowed
      if: ${{ inputs.push == 'true' && github.event_name == 'pull_request' }}
      shell: sh
      run: |
        >&2 echo "Publishing to DockerHub is not allowed on pull_request events."
        >&2 echo "If you still want to build images without pushing them, set the push input to false."
        exit 1

    - name: Checkout shared workflows
      env:
        # In a composite action, these two need to be indirected via the
        # environment, as per the GitHub actions documentation:
        # https://docs.github.com/en/actions/learn-github-actions/contexts
        action_repo: ${{ github.action_repository }}
        action_ref: ${{ github.action_ref }}
      uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with:
        repository: ${{ env.action_repo }}
        ref: ${{ env.action_ref }}
        path: _shared-workflows-build-push-to-dockerhub
        persist-credentials: false

    - name: Login to DockerHub
      if: ${{ inputs.push == 'true' }}
      uses: ./_shared-workflows-build-push-to-dockerhub/actions/dockerhub-login

    # If platforms is specified then also initialize buildx and qemu:
    - name: Set up QEMU
      if: inputs.platforms
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      with:
        driver: ${{ inputs.docker-buildx-driver }}
        buildkitd-config: ${{ runner.environment == 'self-hosted' && '/etc/buildkitd.toml' || '' }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893 # v5.9.0
      with:
        images: ${{ inputs.repository }}
        labels: ${{ inputs.labels }}
        tags: ${{ inputs.tags }}

    # The `context` input is flagged by Zizmor as a [sink]. This means that with
    # the upstream action the user's input to the input ends up in an output,
    # and so if it's not handled properly, it could lead to a template injection
    # attack. In this action, we pass through the inputs, but we don't then pass
    # back the outputs, so we should be fine. Even if we did pass back the
    # outputs, we consider ourselves a proxy, so in that case our job would be
    # to warn users but not to take any action.
    #
    # [sink]: https://github.blog/security/application-security/how-to-secure-your-github-actions-workflows-with-codeql/#models
    - name: Build and push Docker image # zizmor: ignore[template-injection]
      uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
      with:
        context: ${{ inputs.context }}
        platforms: ${{ inputs.platforms }}
        push: ${{ inputs.push }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        file: ${{ inputs.file }}
        build-args: ${{ inputs.build-args }}
        target: ${{ inputs.target }}
        cache-from: ${{ inputs.cache-from }}
        cache-to: ${{ inputs.cache-to }}
        secrets: ${{ inputs.secrets }}
        load: ${{ inputs.load == 'true' }}
