name: Get Vault Secrets
description: Composite action (step) to get secrets from Grafana Labs' Vault instance.
inputs:
  repo_secrets:
    description: |
      Repository-specific secret mapping. Only Grafana Labs employees can list these secrets in Vault.
      These secrets are stored in the `ci/data/repo/grafana/<repo name>/<secret path>` path in Vault.
      Ex:
      ```
      repo_secrets: |
        ENVVAR1=secretpath:key
        ENVVAR2=secretpath:key2
      ```
  common_secrets:
    description: |
      Common secrets mapping. Only Grafana Labs employees can list these secrets in Vault.
      These secrets are stored in the `ci/data/common/<secret path>` path in Vault.
      Ex:
      ```
      repo_secrets: |
        ENVVAR1=secretpath:key
        ENVVAR2=secretpath:key2
      ```

  vault_instance:
    description: |
      The Vault instance to use (`dev` or `ops`). Defaults to `ops`.
    default: ops

  export_env:
    description: |
      Whether to export secrets as environment variables, making them available to all subsequent steps. Defaults to `true`.
    default: "true"

  ignore_missing:
    description: |
      When set to true, prevents the action from failing when a secret does not exist.
    default: "false"

outputs:
  secrets:
    description: "JSON object containing all the secrets"
    value: ${{ toJSON(steps.import-secrets.outputs) }}

runs:
  using: composite
  steps:
    - id: check-vault-instance
      if: inputs.vault_instance != 'dev' && inputs.vault_instance != 'ops'
      shell: sh
      env:
        VAULT_INSTANCE: ${{ inputs.vault_instance }}
      run: |
        echo "Invalid value for vault_instance input: ${VAULT_INSTANCE}. Must be 'dev' or 'ops'."
        exit 1

    # Translate the secrets into a format that the Vault action can understand
    - id: translate-secrets
      shell: bash
      run: "${GITHUB_ACTION_PATH}/translate-secrets.bash"
      env:
        REPO_SECRETS: ${{ inputs.repo_secrets }}
        COMMON_SECRETS: ${{ inputs.common_secrets }}
        REPO: ${{ github.repository }}

    - id: get-github-jwt-token
      uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
      env:
        VAULT_INSTANCE: ${{ inputs.vault_instance }}
      with:
        script: |
          let jwt;
          try {
            jwt = await core.getIDToken(`vault-github-actions-grafana-${process.env.VAULT_INSTANCE}`);
          } catch (error) {
            core.setFailed(`❌ Failed to get OIDC token: ${error.message}`);

            // Provide helpful suggestions
            core.error(`
          🔧 OIDC Token Error - How to Fix:

          This error typically occurs when your workflow lacks proper permissions for OIDC token generation.

          ✅ Solution 1 - Add workflow-level permissions:
          Add this to the top of your workflow YAML file:

          permissions:
            id-token: write
            contents: read

          ✅ Solution 2 - Add job-level permissions:
          Add this to your specific job:

          jobs:
            your-job-name:
              permissions:
                id-token: write
                contents: read

          ✅ Solution 3 - Verify repository configuration:
          - Ensure your repository has OIDC enabled
          - Check that the Vault OIDC provider is configured for your repository

          📚 More info: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect
            `);
            return;
          }

          core.setSecret(jwt);
          core.setOutput("github-jwt",jwt);

      # Get the secrets
    - name: Import Secrets
      id: import-secrets
      uses: hashicorp/vault-action@4c06c5ccf5c0761b6029f56cfb1dcf5565918a3b # v3.4.0
      with:
        url: "https://vault-github-actions.grafana-${{ inputs.vault_instance }}.net/"
        role: vault-github-actions
        path: github-actions-oidc
        method: jwt
        jwtGithubAudience: "https://vault-github-actions.grafana-${{ inputs.vault_instance }}.net"
        extraHeaders: |
          Proxy-Authorization-Token: Bearer ${{ steps.get-github-jwt-token.outputs.github-jwt }}
        secrets: |
          ${{ steps.translate-secrets.outputs.secrets }}
        exportEnv: ${{ inputs.export_env }}
        ignoreNotFound: ${{ inputs.ignore_missing }}
