name: Push to artifact registry
description: Composite action to push to Google Artifact Registry
inputs:
  platforms:
    description: desc
    required: true
outputs:
  resolved_platforms: 
    description: resolved-platform
    value: ${{ steps.print.outputs.processed-platforms }}


# env:
#   platform_env: ${{ inputs.platforms }}

runs:
  using: composite
  steps:
    - name: Checkout shared workflows
      env:
        # In a composite action, these two need to be indirected via the
        # environment, as per the GitHub actions documentation:
        # https://docs.github.com/en/actions/learn-github-actions/contexts
        action_repo: ${{ github.action_repository }}
        action_ref: ${{ github.action_ref }}
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        repository: grafana/shared-workflows
        ref: "multiarch-docker-builds-using-sh-runners"
        path: _shared-workflows-push-to-gar-docker-multi-arch
    - name: env-var
      uses: grafana/shared-workflows/actions/resolve-architectures@multiarch-docker-builds-using-sh-runners
      with: 
        platforms: ${{ inputs.platforms }}
    - name: print
      shell: bash
      run: | 
        processed_platforms="${{ steps.env-var.outputs.resolved_platforms }}"
        echo "processed-platforms=${processed_platforms}" >> $GITHUB_OUTPUT
        echo "Processed platforms: ${processed_platforms}"
