name: Checkout and lint pull request title
description: Ensure your PR title matches the requirements in the commitlint config.

runs:
  using: composite
  steps:
    - name: Check out the repo
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Run lint on the PR title
      uses: grafana/shared-workflows/actions/lint-pr-title-js@yduartep/add-lint-pr-title-workflow
