name: Lint pull request title using Javascript
description: Run lint on the PR title to check if It matches the commitlint specification.

inputs:
  config-path:
    default: "./commitlint.config.js"
    description: "Path to the commitlint configuration file, relative to the action's directory."
    required: false

  title-only:
    default: "true"
    description: "Check only the PR/commit title. If false, it will check the whole PR/commit message."
    required: false

runs:
  using: "composite"
  steps:
    - name: Checkout shared-workflows repository
      env:
        action_repo: "${{ github.action_repository || 'grafana/shared-workflows' }}"
        action_ref: ${{ github.action_ref }}
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: ${{ env.action_repo }}
        ref: ${{ env.action_ref }}
        path: _shared-workflows-lint-pr-title
        persist-credentials: false

    - name: Install bun package manager
      uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
      with:
        bun-version-file: _shared-workflows-lint-pr-title/.bun-version

    - name: Install dependencies
      shell: sh
      working-directory: _shared-workflows-lint-pr-title
      run: |
        bun install --frozen-lockfile --production --filter lint-pr-title

    - name: Lint PR title
      shell: sh
      working-directory: _shared-workflows-lint-pr-title/actions/lint-pr-title
      env:
        GITHUB_TOKEN: ${{ github.token }}
        INPUT_CONFIG_PATH: ${{ inputs.config-path }}
        INPUT_TITLE_ONLY: ${{ inputs.title-only }}
        NODE_ENV: "production"
      run: |
        bun run src/index.ts

branding:
  icon: "shield"
  color: "green"
