name: Export and Upload Docker Manifest
description: Composite action to export and upload a docker manifest

inputs:
  digest:
    description: |
      Docker digest.
      This is included as an output for `docker-build-push-image` and `docker/build-push-action`.
    required: true
  platform:
    description: |
      Docker platform, ex: linux/arm64.
    required: true

runs:
  using: composite
  steps:
    - name: Prepare
      id: prepare
      shell: bash
      env:
        PLATFORM: ${{ inputs.platform }}
      run: |
        echo "platform-pair=${PLATFORM//\//-}" | tee -a "${GITHUB_OUTPUT}"

    - name: Export digest
      shell: sh
      run: |
        mkdir -p ${{ runner.temp }}/digests
        digest="${STEPS_BUILD_OUTPUTS_DIGEST}"
        touch "${{ runner.temp }}/digests/${digest#sha256:}"

        ls -lah ${{ runner.temp }}/digests
      env:
        STEPS_BUILD_OUTPUTS_DIGEST: ${{ inputs.digest }}

    - name: Upload digest
      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
      with:
        name: digests-${{ steps.prepare.outputs.platform-pair }}
        path: ${{ runner.temp }}/digests/*
        if-no-files-found: error
        retention-days: 1
