name: Validate Renovate Config
description: Validates Renovate configuration files using renovate-config-validator

inputs:
  path:
    description: Path to the Renovate config file to validate (e.g., 'renovate.json')
    required: false
    default: renovate.json

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: "24"

    - name: Validate Renovate config
      shell: bash
      run: npx --yes --package ${RENOVATE_VERSION} -- renovate-config-validator "${CONFIG_PATH}"
      env:
        CONFIG_PATH: ${{ inputs.path }}
        RENOVATE_VERSION: renovate@41.159
