name: Generate OpenAPI client
description: Takes in a locally stored OpenAPI spec and generates a client from it

inputs:
  generator-version:
    description: "The version of the OpenAPI generator to use"
    required: false
    default: "7.7.0"
  spec-path:
    description: "The path to the OpenAPI spec to generate the client from"
    required: true
  output-dir:
    description: "The directory to output the generated client to"
    required: false
    default: "."
  commit-changes:
    description: If true, the action will commit and push the changes to the repository, if there's a diff.
    required: false
    default: "true"
  commit-message:
    description: The commit message to use when committing the changes
    required: false
    default: "Update clients and publish"
  package-name:
    description: The name of the package to generate
    required: true

runs:
  using: composite
  steps:
    # Get the repository name
    - shell: bash
      run: echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV

    # Get openapi-generator
    - id: openapi-generator-cache
      uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        key: openapi-generator-${{ inputs.generator-version }}
        path: openapi-generator-cli.jar
    - shell: bash
      if: steps.openapi-generator-cache.outputs.cache-hit != 'true'
      run: |
        wget -nv "https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/${{ inputs.generator-version }}/openapi-generator-cli-${{ inputs.generator-version }}.jar" -O ./openapi-generator-cli.jar
    - uses: actions/cache/save@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      if: steps.openapi-generator-cache.outputs.cache-hit != 'true'
      with:
        key: openapi-generator-${{ inputs.generator-version }}
        path: openapi-generator-cli.jar

    # Generate the client
    - shell: bash
      run: ${GITHUB_ACTION_PATH}/generate.sh
      env:
        SPEC_PATH: ${{ inputs.spec-path }}
        OUTPUT_DIR: ${{ inputs.output-dir }}
        PACKAGE_NAME: ${{ inputs.package-name }}

    # Delete the openapi-generator-cli.jar file (it shouldn't be committed)
    - shell: bash
      run: rm openapi-generator-cli.jar

    # Commit the changes
    - uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5.0.1
      if: ${{ inputs.commit-changes == 'true' }}
      with:
        commit_message: ${{ inputs.commit-message }}
