name: Resolve architectures for Docker image builds
description: Composite action to resolve architectures for Docker image builds
inputs:
  platforms:
    description: platform
    required: true
outputs:
  resolved_platforms: 
    description: Resolved platform architectures
    value: ${{ steps.resolve-platforms-names.outputs.resolved_platforms }}
  
runs:
  using: composite
  steps:
    - name: Resolve platform name
      id: resolve-platforms-names
      shell: bash
      run: |
        declare -a arr=()
          
        for platform_input in $(echo "${{ inputs.platforms }}" | sed "s/,/ /g")
        do
          platform=$(echo ${platform_input} | cut -d "/" -f 2)
          if [ "${platform}" == "arm64" ]; then
            arr+=("arm64")
          elif [ "${platform}" == "amd64" ]; then
            arr+=("x64")
          else
            echo "Invalid architecture. Valid architectures: arm64, amd64"
            exit 1
          fi
        done

        arr_string=$(IFS=, ; echo "['${arr[*]}']")
        ARR_STRING=$(echo $arr_string | sed "s/,/','/g")
        echo "resolved_platforms=${ARR_STRING}" >> ${GITHUB_OUTPUT}

        echo "Resolved platforms: ${ARR_STRING}"

    - name: Print resolved platforms inside action
      shell: bash
      run: |
        echo "Inside composite action - Resolved platforms: ${{ steps.resolve-platforms-names.outputs.resolved_platforms }}"
