name: Export SPDX SBOM from Socket.dev API
description: Export SPDX SBOM from Socket.dev API for a given repository.

inputs:
  socket_api_token:
    description: "Socket API token for authentication"
    required: true
  socket_base_url:
    description: "Socket base url"
    required: false
    default: "https://api.socket.dev/v0"
  socket_org:
    description: "Socket org name"
    required: true
    default: "grafana"
  output_file:
    description: "Name of the file to save the sbom"
    required: false

outputs:
  path:
    description: "Path to the exported sbom file"
    value: ${{ steps.export-sbom.outputs.path }}

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
      with:
        go-version: "1.25.5"

    - name: Extract repository name
      id: repo-name
      shell: bash
      run: |
        REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
        echo "name=$REPO_NAME" >> $GITHUB_OUTPUT

    - name: Export SPDX SBOM from Socket.dev
      id: export-sbom
      shell: bash
      env:
        SOCKET_API_TOKEN: ${{ inputs.socket_api_token }}
        SOCKET_BASE_URL: ${{ inputs.socket_base_url }}
        SOCKET_ORG: ${{ inputs.socket_org }}
        REPO_NAME: ${{ steps.repo-name.outputs.name }}
        OUTPUT_FILE: ${{ inputs.output_file }}
        ACTION_PATH: ${{ github.action_path }}
      run: |
        # Extract basename if output_file is provided (handles both filenames and paths)
        if [[ -n "$OUTPUT_FILE" ]]; then
          OUTPUT_FILE=$(basename "$OUTPUT_FILE")
        fi
        cd "$ACTION_PATH"
        go run ./cmd/export-sbom/ "$REPO_NAME" "${ACTION_PATH}/${OUTPUT_FILE}"
        echo "path=$ACTION_PATH/$OUTPUT_FILE" >> $GITHUB_OUTPUT
