name: Setup Conftest
description: Setup conftest and add it to the PATH, this action will pull the binary from GitHub releases and store it in cache for the next run.

inputs:
  version:
    description: |
      Version of conftest to install.
    default: 0.55.0

runs:
  using: composite

  steps:
    - name: Setup cache
      id: cache
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      with:
        path: /usr/local/bin/conftest
        key: conftest-${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}

    - if: runner.os == 'macOS'
      shell: sh
      run: echo "OS=Darwin" >> "$GITHUB_ENV"

    # runner.arch options: X86, X64, ARM, or ARM64.
    # conftest release: arm64, x86_64, ppc64le, s390x.
    # If it ain't arm64 or x86_64, it'll fall back to runner.arch.
    - if: runner.arch == 'X64'
      shell: sh
      run: echo "ARCH=x86_64" >> "$GITHUB_ENV"

    - if: runner.arch == 'ARM64'
      shell: sh
      run: echo "ARCH=arm64" >> "$GITHUB_ENV"

    - name: Fetch Github Release Asset
      id: fetch_asset
      if: steps.cache.outputs.cache-hit != 'true'
      uses: dsaltares/fetch-gh-release-asset@aa2ab1243d6e0d5b405b973c89fa4d06a2d0fff7 # 1.1.2
      with:
        repo: "open-policy-agent/conftest"
        version: "tags/v${{ inputs.version }}"
        file: "conftest_${{ inputs.version }}_${{ env.OS || runner.os }}_${{ env.ARCH || runner.arch }}.tar.gz"
        target: ${{ runner.temp }}/conftest.tgz

    - name: Unpack tarball
      id: unpack
      if: steps.fetch_asset.outcome == 'success'
      shell: sh
      run: |
        tar -zxvf ${{ runner.temp }}/conftest.tgz conftest
        mv conftest /usr/local/bin
        chmod +x /usr/local/bin/conftest
