name: Setup Conftest
description: Setup conftest and add it to the PATH, this action will pull the binary from GitHub releases and store it in cache for the next run.

inputs:
  version:
    description: |
      Version of conftest to install.
    default: 0.55.0

runs:
  using: composite

  steps:
    - name: Restore cache
      id: restore
      uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: ${{ github.workspace }}/bin/conftest
        key: conftest-${{ runner.os }}-${{ runner.arch }}-${{ inputs.version }}

    - name: Fetch Github Release Asset
      id: fetch_asset
      if: steps.restore.outputs.cache-hit != 'true'
      uses: dsaltares/fetch-gh-release-asset@a40c8b4a0471f9ab81bdf73a010f74cc51476ad4 # 1.1.1
      with:
        repo: "open-policy-agent/conftest"
        version: "tags/v${{ inputs.version }}"
        file: "conftest_${{ inputs.version }}_${{ runner.os }}_${{ runner.arch }}.tar.gz"
        target: ${{ github.workspace }}/bin/conftest.tgz

    - name: Unpack tarball
      id: unpack
      if: steps.fetch_asset.outcome == 'success'
      shell: sh
      run: |
        tar -zxvf ${{ github.workspace }}/bin/conftest.tgz conftest
        mv conftest ${{ github.workspace }}/bin
        chmod +x ${{ github.workspace }}/bin/conftest

    - name: Save to cache
      id: save
      if: steps.unpack.outcome == 'success'
      uses: actions/cache/save@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
      with:
        path: ${{ github.workspace }}/bin/conftest
        key: ${{ steps.restore.outputs.cache-primary-key }}

    - name: Add binary to path
      shell: sh
      run: |
        echo "${{ github.workspace }}/bin" >> $GITHUB_PATH
