name: Lint Argo Workflow files
description: Lint Argo workflow files

inputs:
  path:
    description: |
      Path to files for linting.
    required: true

runs:
  using: composite

  steps:
    - name: Install argo-cli
      uses: grafana/shared-workflows/actions/install-argo-cli@main

    - name: Run
      shell: bash
      run: argo lint --offline ${{ inputs.path }}
