name: Lint Argo Workflow files
description: Lint Argo workflow files

inputs:
  path:
    description: |
      Path to files for linting.
    required: true
  argo-version:
    description: |
      Version of the Argo CLI to use for linting.
    default: "3.7.10"

runs:
  using: composite

  steps:
    - name: Setup Argo
      uses: grafana/shared-workflows/actions/setup-argo@21cbef8182ef0fc1c3ae8e68b9590af49ed10a5b # setup-argo/v1.2.1
      with:
        version: ${{ inputs.argo-version }}

    - name: Run
      env:
        WORKFLOW_PATH: ${{ inputs.path }}
      shell: bash
      run: argo lint --offline "${WORKFLOW_PATH}"
