name: Lint Argo Workflow files
description: Lint Argo workflow files

inputs:
  path:
    description: |
      Path to files for linting.
    required: true

runs:
  using: composite

  steps:
    - name: Checkout
      env:
        # In a composite action, these two need to be indirected via the
        # environment, as per the GitHub actions documentation:
        # https://docs.github.com/en/actions/learn-github-actions/contexts
        action_repo: "${{ github.action_repository || 'grafana/shared-workflows' }}"
        action_ref: ${{ github.action_ref }}
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        repository: ${{ env.action_repo }}
        ref: ${{ env.action_ref }}
        path: _shared-workflows-argo-lint

    - name: Install argo-cli
      uses: ./_shared-workflows-argo-lint/actions/install-argo-cli

    - name: Run
      env:
        WORKFLOW_PATH: ${{ inputs.path }}
      shell: bash
      run: argo lint --offline "${WORKFLOW_PATH}"
