name: Push to artifact registry
description: Composite action to push to Google Artifact Registry
inputs:
  registry:
    description: |
      Google Artifact Registry to store docker images in.
  tags:
    description: |
      List of Docker images to be pushed.
  build_path:
    description: |
      Path to Dockerfile, which is used to build the image.
  environment:
    description: |
      Environment for pushing artifacts (can be either dev or prod).
    default: dev

runs:
  using: composite
  steps:
    - uses: google-github-actions/auth@v1
      id: gcloud-auth
      with:
        token_format: access_token
        workload_identity_provider: "projects/304398677251/locations/global/workloadIdentityPools/github/providers/github-provider"
        service_account: "github-docker-dev@grafanalabs-workload-identity.iam.gserviceaccount.com"
        create_credentials_file: false
    - name: Login to GAR
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: oauth2accesstoken
        password: ${{ steps.gcloud-auth.outputs.access_token }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.0.0
    - name: Build the container
      uses: docker/build-push-action@v5.0.0
      with:
        context: ${{ inputs.build_path }}
        push: ${{ github.event_name == 'push' }}
        tags: ${{ inputs.tags }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
