name: Push to cloud storage
description: Composite action to push to Google Cloud Storage
inputs:
  bucket:
    description: |
      Name of bucket to upload to. Will default to grafanalabs-${repository.name}-${environment}
    default: ""
  path:
    description: |
      The path to a file or folder inside the action's filesystem
      that should be uploaded to the bucket.
      You can specify either the absolute path or the relative path from the action.
    required: true
  bucket_path:
    description: |
      Bucket path where objects will be uploaded. Default is the bucket root.
    default: ""
  environment:
    description: |
      Environment for uploading objects (can be either dev or prod).
    default: dev
  glob:
    description: |
      Glob pattern.
  parent:
    description: |
      Whether parent dir should be included in GCS destination.
      Dirs included in the `glob` statement are unaffected by this setting.
    default: "true"
  predefinedAcl:
    description: |
      Apply a predefined set of access controls to the file(s).
      Default is projectPrivate (See https://googleapis.dev/nodejs/storage/latest/global.html#UploadOptions)
    default: projectPrivate

outputs:
  uploaded:
    description: "The list of successfully uploaded files."
    value: ${{ steps.upload-files.outputs.uploaded }}

runs:
  using: composite
  steps:
    - name: Checkout
      env:
        action_repo: ${{ github.action_repository }}
        action_ref: ${{ github.action_ref }}
      uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      with:
        repository: ${{ env.action_repo }}
        ref: ${{ env.action_ref }}
        path: shared-workflows
    - name: Resolve GCP project
      id: resolve-project
      shell: bash
      run: |
        if [[ "${{ inputs.environment }}" == "dev" ]]; then
          PROJECT="grafanalabs-dev"
        elif [[ "${{ inputs.environment }}" == "prod" ]]; then
          PROJECT="grafanalabs-global"
        else
          echo "Invalid environment. Valid environment variable inputs: dev, prod"
          exit 1
        fi
        echo "project=${PROJECT}" | tee -a ${GITHUB_OUTPUT}
    - name: Login to GCS
      id: login-to-gcs
      uses: ./shared-workflows/actions/login-to-gcs
      with:
        bucket: ${{ inputs.bucket }}
        environment: ${{ inputs.environment }}
    - name: Construct path
      id: construct-path
      shell: bash
      env:
        bucket: ${{ steps.login-to-gcs.outputs.bucket }}
      run: |
        # Join bucket name with bucket_path (Ex: bucket_name/path/to/file)
        DESTINATION="${{ env.bucket }}/${{ inputs.bucket_path }}"
        DESTINATION="${DESTINATION%/}"  # strip trailing /

        echo "destination=${DESTINATION}" | tee -a ${GITHUB_OUTPUT}
    - uses: google-github-actions/upload-cloud-storage@e485962f2bef914ac9c3bdd571f821f0ba7946c4 # v2.2.0
      id: upload-files
      with:
        path: ${{ inputs.path }}
        glob: ${{ inputs.glob }}
        destination: ${{ steps.construct-path.outputs.destination }} # bucket name plus folder prefix (if applicable)
        parent: ${{ inputs.parent }}
        predefinedAcl: ${{ inputs.predefinedAcl }}
        process_gcloudignore: false
