name: Push to cloud storage
description: Composite action to push to Google Cloud Storage
inputs:
  bucket:
    description: |
      Name of bucket to upload to. Will default to grafanalabs-${repository.name}-${environment}
    default: ""
  path:
    description: |
      The path to a file or folder inside the action's filesystem
      that should be uploaded to the bucket.
      You can specify either the absolute path or the relative path from the action.
    required: true
  bucket_path:
    description: |
      Bucket path where objects will be uploaded. Default is the bucket root.
    default: ""
  environment:
    description: |
      Environment for uploading objects (can be either dev or prod).
    default: dev
  glob:
    description: |
      Glob pattern.
  parent:
    description: |
      Whether parent dir should be included in GCS destination.
      Dirs included in the `glob` statement are unaffected by this setting.
    default: "true"
  predefinedAcl:
    description: |
      Apply a predefined set of access controls to the file(s).
      Default is projectPrivate (See https://googleapis.dev/nodejs/storage/latest/global.html#UploadOptions)
    default: projectPrivate
  service_account:
    description: |
      Custom service account to use for authentication.
    default: ""
  delete_credentials_file:
    description: |
      Delete the credentials file after the action is finished.
      If you want to keep the credentials file for a later step, set this to false.
    default: "true"

outputs:
  uploaded:
    description: "The list of successfully uploaded files."
    value: ${{ steps.upload-files.outputs.uploaded }}

runs:
  using: composite
  steps:
    - name: Checkout
      env:
        action_repo: ${{ github.action_repository }}
        action_ref: ${{ github.action_ref }}
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        repository: ${{ env.action_repo }}
        ref: ${{ env.action_ref }}
        path: _shared-workflows-push-to-gcs
        persist-credentials: false
    - name: Resolve GCP project
      id: resolve-project
      shell: bash
      env:
        ENVIRONMENT: ${{ inputs.environment }}
      run: |
        if [[ "${ENVIRONMENT}" == "dev" ]]; then
          PROJECT="grafanalabs-dev"
        elif [[ "${ENVIRONMENT}" == "prod" ]]; then
          PROJECT="grafanalabs-global"
        else
          echo "Invalid environment. Valid environment variable inputs: dev, prod"
          exit 1
        fi
        echo "project=${PROJECT}" | tee -a ${GITHUB_OUTPUT}
    - name: Login to GCS
      id: login-to-gcs
      uses: ./_shared-workflows-push-to-gcs/actions/login-to-gcs
      with:
        bucket: ${{ inputs.bucket }}
        environment: ${{ inputs.environment }}
        service_account: ${{ inputs.bucket && inputs.service_account || '' }}
        delete_credentials_file: false
    - name: Construct path
      id: construct-path
      shell: bash
      env:
        BUCKET: ${{ steps.login-to-gcs.outputs.bucket }}
        BUCKET_PATH: ${{ inputs.bucket_path }}
      run: |
        # Join bucket name with bucket_path (Ex: bucket_name/path/to/file)
        DESTINATION="${BUCKET}/${BUCKET_PATH}"
        DESTINATION="${DESTINATION%/}"  # strip trailing /

        echo "destination=${DESTINATION}" | tee -a ${GITHUB_OUTPUT}
    - uses: google-github-actions/upload-cloud-storage@7c6e11cb7291594c5dfe0bc1dd9cd905e31e600c # v2.2.2
      id: upload-files
      with:
        path: ${{ inputs.path }}
        glob: ${{ inputs.glob }}
        destination: ${{ steps.construct-path.outputs.destination }} # bucket name plus folder prefix (if applicable)
        parent: ${{ inputs.parent }}
        predefinedAcl: ${{ inputs.predefinedAcl }}
        process_gcloudignore: false

    - name: Cleanup checkout directory
      if: ${{ !cancelled() }}
      shell: bash
      run: |
        # Check that the directory looks OK before removing it
        if ! [ -d "_shared-workflows-push-to-gcs/.git" ]; then
          echo "::warning Not removing shared workflows directory: doesn't look like a git repository"
          exit 0
        fi
        rm -rf _shared-workflows-push-to-gcs

    - name: Delete Google Application Credentials file
      if: ${{ inputs.delete_credentials_file == 'true' && env.GOOGLE_APPLICATION_CREDENTIALS != '' }}
      shell: sh
      run: |
        if [ -f "${{ env.GOOGLE_APPLICATION_CREDENTIALS }}" ]; then
          rm -f "${{ env.GOOGLE_APPLICATION_CREDENTIALS }}"
          echo "::notice::Successfully deleted credentials file"
        else
          echo "::warning::Credentials file not found at ${{ env.GOOGLE_APPLICATION_CREDENTIALS }}"
        fi
