name: Push to cloud storage
description: Composite action to push to Google Cloud Storage
inputs:
  bucket:
    description: |
      Name of bucket to upload to. This is output from the login-to-gcs shared-workflow.
    required: true
  path:
    description: |
      Path to the object(s) to upload. Can either include a filename to upload 1 file,
      or can be used in conjunction with the `glob` option to upload files from a path.
      Valid examples include `thing.txt` and `path/to/thing.txt`.
      Valid examples when also using `glob` include `path/to`.
    required: true
  bucket_path:
    description: |
      The path in the bucket to save the object(s). Defaults to the root of the bucket.
    default: ""
  environment:
    description: |
      Environment for uploading objects (can be either dev or prod).
    default: dev
  parent:
    description: |
      Whether parent directory should be included in bucket.

outputs:
  uploaded:
    description: "The list of successfully uploaded files."
    value: ${{ steps.upload-files.outputs.uploaded }}

runs:
  using: composite
  steps:
    - name: Resolve GCP project
      id: resolve-project
      shell: bash
      run: |
        if [ "${{ inputs.environment }}" = "dev" ]; then
          PROJECT="grafanalabs-dev"
        elif [ "${{ inputs.environment }}" == "prod" ]; then
          PROJECT="grafanalabs-global"
        else
          echo "Invalid environment. Valid environment variable inputs: dev, prod"
          exit 1
        fi
        echo "project=${PROJECT}" >> ${GITHUB_OUTPUT}
    - name: Construct path
      id: construct-path
      shell: bash
      run: |
        # Check for wildcard and set glob if exists
        if [[ "${{ inputs.path }}" == *"*"* ]]; then
          GLOB="${{ inputs.path }}"
          PATH="."
        else
          GLOB=""
          PATH="${{ inputs.path }}"
        fi

        # Then, join together bucket_path with bucket_name (Ex: bucket_name/path/to/file)
        DESTINATION="${{ inputs.bucket }}/${{ inputs.bucket_path }}"
        DESTINATION="${DESTINATION%/}"  # strip trailing /

        echo "Setting glob to ${GLOB}"
        echo "glob=${GLOB}" >> ${GITHUB_OUTPUT}
        echo "Setting path to ${PATH}"
        echo "path=${PATH}" >> ${GITHUB_OUTPUT}
        echo "Setting destination to ${DESTINATION}"
        echo "destination=${DESTINATION}" >> ${GITHUB_OUTPUT}
    - uses: google-github-actions/upload-cloud-storage@22121cd842b0d185e042e28d969925b538c33d77 # v2.1.0
      id: upload-files
      with:
#        path: ${{ steps.construct-path.outputs.path }}
#        glob: ${{ steps.construct-path.outputs.glob }}
        path: "."
        glob: ${{ inputs.path }}
        destination: ${{ steps.construct-path.outputs.destination }} # bucket name plus folder prefix (if applicable)
        parent: ${{ inputs.parent }}
        process_gcloudignore: false
