name: Push to cloud storage
description: Composite action to push to Google Cloud Storage
inputs:
  object:
    description: |
      Name of object to upload.
    required: true
  destination:
    description: |
      Location to upload object (including object name). Will create sub-folders in the bucket.
      Default behavior is to upload ${inputs.object} to the root folder of the bucket.
    default: ""
  environment:
    description: |
      Environment for uploading objects (can be either dev or prod).
    default: dev

runs:
  using: composite
  steps:
    - name: Resolve GCP project
      id: resolve-project
      shell: bash
      run: |
        if [ "${{ inputs.environment }}" == 'dev' ]; then
          PROJECT="grafanalabs-dev"
        elif [ "${{ inputs.environment }}" == 'prod' ]; then
          PROJECT="grafanalabs-global"
        else
          echo "Invalid environment. Valid environment variable inputs: dev, prod"
          exit 1
        fi
        echo "project=${PROJECT}" >> ${GITHUB_OUTPUT}
    - name: Get object name and location
      id: get-object-location
      shell: sh
      run: echo "object_path=${{ inputs.destination != '' && inputs.destination || inputs.object }}" >> ${GITHUB_OUTPUT}
    - name: Construct service account and bucket name
      id: construct-gcs-vars
      shell: sh
      run: |
        # construct service account name
        SERVICE_ACCOUNT="github-${{ github.repository_id }}-${{ inputs.environment }}-gcs@grafanalabs-workload-identity.iam.gserviceaccount.com"
        echo "service_account=${SERVICE_ACCOUNT}" >> ${GITHUB_OUTPUT}

        # construct bucket name
        BUCKET_NAME="grafanalabs-${{ github.repository_id }}-${{ inputs.environment }}
        echo "bucket_name=${BUCKET_NAME}" >> ${GITHUB_OUTPUT}

        # construct path
        echo "object_path=${{ inputs.destination != '' && inputs.destination || inputs.object }}" >> ${GITHUB_OUTPUT}
    - uses: google-github-actions/auth@5a50e581162a13f4baa8916d01180d2acbc04363 # v2.1.0
      id: gcloud-auth
      with:
        token_format: access_token
        workload_identity_provider: "projects/304398677251/locations/global/workloadIdentityPools/github/providers/github-provider"
        service_account: ${{ steps.construct-gcs-vars.outputs.service_account }}
        create_credentials_file: false
    - uses: google-github-actions/upload-cloud-storage@22121cd842b0d185e042e28d969925b538c33d77 # v2.1.0
      id: upload-files
      with:
        path: ${{ steps.construct-gcs-vars.outputs.object_path }}
        destination: ${{ steps.construct-gcs-vars.outputs.bucket_name }}
