name: Send Slack Message
description: Composite action to send a Slack message

inputs:
  payload:
    description: "JSON payload to send"
    required: false
  method:
    description: "The Slack API method to call"
    required: true
  payload-templated:
    description: "To replace templated variables provided from the step env or default GitHub event context and payload, set the payload-templated variable to true"
    required: false
outputs:
  time:
    value: ${{ steps.send-slack-message.outputs.time }}
    description: "The time that the Slack message was sent"
  thread_ts:
    value: ${{ steps.send-slack-message.outputs.thread_ts }}
    description: "The timestamp on the latest thread posted into Slack"
  ts:
    value: ${{ steps.send-slack-message.outputs.ts }}
    description: "The timestamp on the message that was posted into Slack"
  channel_id:
    value: ${{ steps.send-slack-message.outputs.channel_id }}
    description: "The channel id of the message that was posted into Slack"

runs:
  using: composite
  steps:
    - name: Checkout shared workflows
      env:
        action_repo: ${{ github.action_repository }}
        action_ref: ${{ github.action_ref }}
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: ${{ env.action_repo }}
        ref: ${{ env.action_ref }}
        path: _shared-workflows-slack
        persist-credentials: false

    - name: Get a Slack token
      uses: ./_shared-workflows-slack/actions/get-vault-secrets
      with:
        common_secrets: |
          SLACK_BOT_TOKEN=slack-notifications:oauth-token
    - name: Send Slack Message
      id: send-slack-message
      uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
      with:
        payload-templated: ${{ inputs.payload-templated }}
        method: ${{ inputs.method }}
        payload: ${{ inputs.payload }}
        token: ${{ env.SLACK_BOT_TOKEN }}

    # Cleanup checkout directory
    - name: Cleanup shared workflows checkout
      if: ${{ !cancelled() }}
      shell: bash
      run: |
        # Check that the directory looks OK before removing it
        if ! [ -d "_shared-workflows-slack/.git" ]; then
          echo "::warning Not removing shared workflows directory: doesn't look like a git repository"
          exit 0
        fi
        rm -rf _shared-workflows-slack
