name: Send Slack Message
description: Composite action to send a Slack message

inputs:
  payload:
    description: "JSON payload to send. Use `payload` or `slack-message`, but not both"
    required: false
  method:
    description: "The Slack API method to call"
    required: true
  payload-templated:
    description: "To replace templated variables provided from the step env or default GitHub event context and payload, set the payload-templated variable to true"
    required: false
outputs:
  time:
    value: ${{ steps.send-slack-message.outputs.time }}
    description: "The time that the Slack message was sent"
  thread_ts:
    value: ${{ steps.send-slack-message.outputs.thread_ts }}
    description: "The timestamp on the latest thread posted into Slack"
  ts:
    value: ${{ steps.send-slack-message.outputs.ts }}
    description: "The timestamp on the message that was posted into Slack"
  channel_id:
    value: ${{ steps.send-slack-message.outputs.channel_id }}
    description: "The channel id of the message that was posted into Slack"

runs:
  using: composite
  steps:
    - name: Get a Slack token
      uses: grafana/shared-workflows/actions/get-vault-secrets@main
      with:
        common_secrets: |
          SLACK_BOT_TOKEN=slack-notifications:oauth-token
    - name: Send Slack Message
      id: send-slack-message
      uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d # v2.0.0
      with:
        payload-templated: ${{ inputs.payload-templated }}
        method: ${{ inputs.method }}
        payload: ${{ inputs.payload }}
        token: ${{ env.SLACK_BOT_TOKEN }}
