name: Send Slack Message
description: Composite action to send a Slack message

inputs:
  payload:
    description: "JSON payload to send"
    required: false
  method:
    description: "The Slack API method to call"
    required: true
  payload-templated:
    description: "To replace templated variables provided from the step env or default GitHub event context and payload, set the payload-templated variable to true"
    required: false
    default: "false"
outputs:
  time:
    value: ${{ steps.send-slack-message.outputs.time }}
    description: "The time that the Slack message was sent"
  thread_ts:
    value: ${{ steps.send-slack-message.outputs.thread_ts }}
    description: "The timestamp on the latest thread posted into Slack"
  ts:
    value: ${{ steps.send-slack-message.outputs.ts }}
    description: "The timestamp on the message that was posted into Slack"
  channel_id:
    value: ${{ steps.send-slack-message.outputs.channel_id }}
    description: "The channel id of the message that was posted into Slack"

runs:
  using: composite
  steps:
    - id: get-secrets
      name: Get a Slack token
      uses: grafana/shared-workflows/actions/get-vault-secrets@e46fe1e9a2bf9e618bcf8d8d32f3a7381b45c06d # get-vault-secrets/v2.0.0
      with:
        common_secrets: |
          SLACK_BOT_TOKEN=slack-notifications:oauth-token

    - name: Send Slack Message
      id: send-slack-message
      uses: slackapi/slack-github-action@0d95c9a7becc1e6e297d76df9bc735c44f4cbcbc # v3.0.5
      with:
        payload-templated: ${{ inputs.payload-templated }}
        method: ${{ inputs.method }}
        payload: ${{ inputs.payload }}
        token: ${{ fromJSON(steps.get-secrets.outputs.secrets).SLACK_BOT_TOKEN }}
