name: Login to artifact registry
description: Composite action to push to Google Artifact Registry
inputs:
  registry:
    description: |
      Google Artifact Registry to authenticate against.
    default: "us-docker.pkg.dev"

  workspace_credentials:
    description: |
      Keep credentials file in workspace for Docker action compatibility. When
      false (default), credentials are moved to a temporary location so they
      aren't in the working directory where they can be accidentally committed
      or printed. Set to true if you need to use Docker-based GitHub Actions that
      require workspace access in a later step.
    default: "false"

runs:
  using: composite
  steps:
    - uses: google-github-actions/auth@ba79af03959ebeac9769e648f473a284504d9193 # v2.1.10
      name: Auth with direct WIF
      id: auth_with_direct_wif
      with:
        project_id: "grafanalabs-workload-identity"
        workload_identity_provider: "projects/304398677251/locations/global/workloadIdentityPools/github/providers/github-provider"
        create_credentials_file: true

    - name: "Move credentials to temporary location"
      if: inputs.workspace_credentials == 'false'
      shell: sh
      env:
        ORIGINAL_CREDS_PATH: ${{ steps.auth_with_direct_wif.outputs.credentials_file_path }}
      # `github-env` is firing for our additions in here. We create this
      # direcotry and populate it, so this should be as safe as we can make it.
      run: | # zizmor: ignore[github-env]
        TEMP_CREDS_DIR="$(mktemp -d -p "${RUNNER_TEMP}")"
        TEMP_CREDS_PATH="${TEMP_CREDS_DIR}/gcp-credentials.json"

        if ! [ -f "${ORIGINAL_CREDS_PATH}" ]; then
          echo "::error::Expected credentials file not found at ${ORIGINAL_CREDS_PATH}"
          exit 1
        fi

        echo "::notice::Moving credentials out of GitHub workspace"
        mv "${ORIGINAL_CREDS_PATH}" "${TEMP_CREDS_PATH}"

        # Update environment for subsequent steps
        echo "CLOUDSDK_AUTH_CREDENTIAL_FILE_OVERRIDE=${TEMP_CREDS_PATH}" | tee -a "${GITHUB_ENV}"
        echo "GOOGLE_APPLICATION_CREDENTIALS=${TEMP_CREDS_PATH}" | tee -a "${GITHUB_ENV}"
        echo "GOOGLE_GHA_CREDS_PATH=${TEMP_CREDS_PATH}" | tee -a "${GITHUB_ENV}"

        echo "::notice::Credentials stored in ${TEMP_CREDS_PATH}"

    - name: Setup `gcloud` CLI
      if: ${{ !steps.check_if_gcloud_is_installed.outputs.gcloud-installed }}
      uses: google-github-actions/setup-gcloud@77e7a554d41e2ee56fc945c52dfd3f33d12def9a # v2.1.4
      with:
        # Accept any version
        version:

    - name: Configure Docker
      shell: sh
      env:
        REGISTRY: ${{ inputs.registry }}
      run: gcloud auth configure-docker "${REGISTRY}"

    - name: "Workspace credentials mode enabled"
      if: inputs.workspace_credentials == 'true'
      shell: sh
      run: |
        echo "::notice::Credentials kept in workspace for Docker action compatibility"
        echo "::warning::Remember to add 'gha-creds-*.json' to your .gitignore to prevent accidental commits"
