name: "Techdocs: Rewrite relative links"
description: Rewrite links inside techdocs pointing to outside resources

inputs:
  default-branch:
    type: string
    required: true
  repo-url:
    type: string
    required: true
  working-directory:
    type: string
    required: true
  dry-run:
    description: |
      Execute link rewriting without updating the underlying files
    type: boolean
    required: false
    default: false
  checkout-path:
    description: |
      Path where the action checks out its own code. If you disable the
      checkout, make sure to set this to where a previous checkout has been
      made to.
    type: string
    default: _action
    required: false
  checkout:
    description: |
      By default this action checks out its own code. If you want to skip this,
      set to false.
    type: boolean
    required: false
    default: true

runs:
  using: composite

  steps:
    - name: Checkout
      if: ${{ !inputs.skip-checkout }}
      env:
        # In a composite action, these two need to be indirected via the
        # environment, as per the GitHub actions documentation:
        # https://docs.github.com/en/actions/learn-github-actions/contexts
        action_repo: ${{ github.action_repository }}
        action_ref: ${{ github.action_ref }}
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        repository: ${{ env.action_repo }}
        ref: ${{ env.action_ref }}
        path: ${{ inputs.checkout-path }}

    - name: Setup go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
      with:
        check-latest: true
        cache-dependency-path: |
          ${{ inputs.checkout-path }}/actions/techdocs-rewrite-relative-links/go.sum
        go-version-file: "${{ inputs.checkout-path }}/actions/techdocs-rewrite-relative-links/go.mod"

    - name: Run
      id: run
      shell: bash
      run: |
        root_dir=$(realpath ${{ inputs.working-directory }})
        cd ${{ inputs.checkout-path }}/actions/techdocs-rewrite-relative-links
        go run . \
        --root-dir=${root_dir} \
        --default-branch=${{inputs.default-branch}} \
        --repo-url=${{inputs.repo-url}} ${{ inputs.dry-run && '--dry-run' || '' }}

    - name: Cleanup
      if: "always() && !inputs.skip-checkout"
      shell: bash
      run: |
        rm -rf ${{ inputs.checkout-path }}
