name: Login to DockerHub
description: Using the shared Grafana Labs DockerHub credentials, log in to DockerHub

runs:
  using: composite
  steps:
    - name: Get secrets for DockerHub login
      id: get-secrets
      uses: grafana/shared-workflows/actions/get-vault-secrets@e46fe1e9a2bf9e618bcf8d8d32f3a7381b45c06d # get-vault-secrets/v2.0.0
      with:
        common_secrets: |
          DOCKERHUB_USERNAME=dockerhub:username
          DOCKERHUB_PASSWORD=dockerhub:password

    - name: Log in to Docker Hub
      uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
      with:
        username: ${{ fromJSON(steps.get-secrets.outputs.secrets).DOCKERHUB_USERNAME }}
        password: ${{ fromJSON(steps.get-secrets.outputs.secrets).DOCKERHUB_PASSWORD }}
