name: Login to DockerHub
description: Using the shared Grafana Labs DockerHub credentials, log in to DockerHub

runs:
  using: composite
  steps:
    - name: Checkout shared workflows
      env:
        # In a composite action, these two need to be indirected via the
        # environment, as per the GitHub actions documentation:
        # https://docs.github.com/en/actions/learn-github-actions/contexts
        action_repo: ${{ github.action_repository }}
        action_ref: ${{ github.action_ref }}
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        repository: ${{ env.action_repo }}
        ref: ${{ env.action_ref }}
        path: _shared-workflows-dockerhub-login
        persist-credentials: false

    - name: Get secrets for DockerHub login
      id: get-secrets
      uses: ./_shared-workflows-dockerhub-login/actions/get-vault-secrets
      with:
        common_secrets: |
          DOCKERHUB_USERNAME=dockerhub:username
          DOCKERHUB_PASSWORD=dockerhub:password

    - name: Log in to Docker Hub
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_PASSWORD }}
