name: zizmor GitHub Actions static analysis
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  zizmor:
    name: Run zizmor from current branch (self test)

    permissions:
      actions: read
      contents: read

      # used in the `job-workflow-ref` job to fetch an OIDC token, which allows
      # the run to determine its ref
      id-token: write

      pull-requests: write
      security-events: write

    uses: ./.github/workflows/reusable-zizmor.yml
  zizmor-offline:
    name: Run zizmor offline for current branch (self test)

    permissions:
      actions: read
      contents: read

      pull-requests: write
      security-events: write

    uses: ./.github/workflows/reusable-zizmor.yml
    with:
      extra-args: --offline --collect=all
