name: Test login-to-gar action

on:
  push:
    branches:
      - main
    paths:
      - "actions/login-to-gar/**"
      - ".github/workflows/test-login-to-gar.yml"

  pull_request:
    paths:
      - "actions/login-to-gar/**"
      - ".github/workflows/test-login-to-gar.yml"

permissions:
  contents: read
  id-token: write

jobs:
  test:
    strategy:
      matrix:
        enviromnent:
          - dev
          - prod
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - name: Test Login to GAR Action
        id: test-login-to-gar
        uses: ./actions/login-to-gar
        with:
          environment: ${{ matrix.enviromnent }}
          registry: "us-docker.pkg.dev"
