name: Lint & test "Lint PR title" action
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/test-typescript-action.yml
      - actions/lint-pr-title/**
      - internal/check-for-non-releasable-actions/**

  pull_request:
    paths:
      - .github/workflows/test-typescript-action.yml
      - actions/lint-pr-title/**
      - internal/check-for-non-releasable-actions/**
    types:
      - edited
      - opened
      - ready_for_review
      - synchronize

  merge_group:

jobs:
  build-lint-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        directory:
          - actions/lint-pr-title
          - internal/check-for-non-releasable-actions

    name: Build, lint, and test `${{ matrix.directory }}`

    defaults:
      run:
        working-directory: ${{ matrix.directory }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install bun package manager
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
        with:
          bun-version-file: "${{ matrix.directory }}/package.json"

      - name: Install lint-pr-title dependencies
        working-directory: ${{ github.workspace }}
        run: bun install --frozen-lockfile

      - name: Lint
        run: bun lint

      - name: Test
        run: bun test
