name: Check for actions and reusable workflows without a release
description: Check for actions and reusable workflows that don't have a release-please configuration.

runs:
  using: "composite"
  steps:
    - name: Install bun package manager
      uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
      with:
        bun-version-file: actions/lint-pr-title/package.json

    - name: Install dependencies
      shell: sh
      working-directory: ${{ github.action_path }}
      run: |
        bun install --frozen-lockfile --production

    - name: Lint PR title
      shell: sh
      working-directory: ${{ github.action_path }}
      env:
        NODE_ENV: "production"
      run: |
        bun run --cwd ../.. internal/check-for-non-releasable-actions/index.ts
